config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :paths => 'users'
  resources :user do
  	resources :clubs do
  		resources :players
  		resources :matches do
  			resources :players
  		end
		  resources :tournaments do
			  resources :players do
	  		  resources :matches do
	  		  	resources :players
          end
	  		end
      end
		end

  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'

end

app/models/club.rb
class Club < ApplicationRecord
	has_many :tournaments
	has_many :matches
	has_many :players
    has_many :club_users
    has_many :users, :through => :club_users
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  before_action :set_club, only: [:show, :edit, :update, :destroy]

  # GET /clubs
  # GET /clubs.json
  def index
    @clubs = current_user.clubs.all
  end

  # GET /clubs/1
  # GET /clubs/1.json
  def show
  end

  # GET /clubs/new
  def new
    @club = current_user.clubs.new
  end

  # GET /clubs/1/edit
  def edit
  end

  # POST /clubs
  # POST /clubs.json
  def create
    @club = current_user.clubs.new(club_params)

    respond_to do |format|
      if @club.save
        ClubUser.create(club_id: @club.id, user_id: current_user.id)
        format.html { redirect_to user_club_path(current_user, @club), notice: 'Club was successfully created.' }
        format.json { render :show, status: :created, location: @club }
      else
        format.html { render :new }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clubs/1
  # PATCH/PUT /clubs/1.json
  def update
    respond_to do |format|
      if @club.update(club_params)
        format.html { redirect_to @club, notice: 'Club was successfully updated.' }
        format.json { render :show, status: :ok, location: @club }
      else
        format.html { render :edit }
        format.json { render json: @club.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clubs/1
  # DELETE /clubs/1.json
  def destroy
    @club.destroy
    respond_to do |format|
      format.html { redirect_to user_clubs_url, notice: 'Club was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_club
      @club = Club.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def club_params
      params.require(:club).permit(:name)
    end
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/views/clubs/_form.html.erb
<%= form_for([current_user, club]) do |f| %>
  <% if club.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(club.errors.count, "error") %> prohibited this club from being saved:</h2>

      <ul>
      <% club.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clubs/edit.html.erb
<h1>Editing Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Show', @club %> |
<%= link_to 'Back', clubs_path %>

app/views/clubs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Clubs</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clubs.each do |club| %>
      <tr>
        <td><%= club.name %></td>
        <td><%= link_to 'Show', user_club_path(current_user, club) %></td>
        <td><%= link_to 'Edit', edit_user_club_path(current_user, club) %></td>
        <td><%= link_to 'Destroy', user_club_path(current_user, club), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Club', new_user_club_path %>

app/views/clubs/new.html.erb
<h1>New Club</h1>

<%= render 'form', club: @club %>

<%= link_to 'Back', user_clubs_path %>

app/views/clubs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @club.name %>
</p>

<div class="col-md-6">
  <h2>Tournaments</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Timelimit</th>
        <th>Format</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @club.tournaments.each do |tournament| %>
        <tr>
          <td><%= tournament.title %></td>
          <td><%= tournament.timelimit %></td>
          <td><%= tournament.format %></td>
          <td><%= link_to 'Show', user_club_tournament_path(current_user, @club, tournament) %></td>
          <td><%= link_to 'Edit', edit_user_club_tournament_path(current_user, @club, tournament) %></td>
          <td><%= link_to 'Destroy', user_club_tournament_path(current_user, @club, tournament), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New tournament', new_user_club_tournament_path(current_user, @club) %> |
  <%= link_to 'Edit', edit_user_club_path(current_user, @club) %> |
  <%= link_to 'Back', user_clubs_path(current_user) %>
</div>

<div class="col-md-6">
  <h2>Players</h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th colspan="2">Name</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @club.players.each do |player| %>
        <tr>
          <td><%= player.firstname %></td>
          <td><%= player.lastname %></td>
          <td><%= link_to 'Show', user_club_player_path(current_user, @club, player) %></td>
          <td><%= link_to 'Edit', edit_user_club_player_path(current_user, @club, player) %></td>
          <td><%= link_to 'Destroy', user_club_player_path(current_user, @club, player), method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'New player', new_user_club_player_path(current_user, @club) %> |
  <%= link_to 'Edit', edit_user_club_path(current_user, @club) %> |
  <%= link_to 'Back', user_clubs_path(current_user) %>
</div>